/*
 * Copyright (c) 2021-2022, Mirko Felice & Maxim Derevyanchenko. All rights reserved.
 * Licensed under the MIT license. See LICENSE file in the project root for details.
 */

package io.github.dronesecurity.dronesystem.drone.domain.drone.alert.objects;

import io.github.dronesecurity.lib.shared.AlertLevel;

/**
 * Alert representing the alert generated by all sensors.
 */
public class SensorSetAlert {

    private final AlertLevel alertLevel;
    private final ProximityAlert proximityAlert;
    private final AccelerometerAlert accelerometerAlert;
    private final CameraAlert cameraAlert;

    /**
     * Build the sensor set alert.
     * @param alertLevel {@link AlertLevel} to set
     * @param proximityAlert {@link ProximityAlert} to set
     * @param accelerometerAlert {@link AccelerometerAlert} to set
     * @param cameraAlert {@link CameraAlert} to set
     */
    public SensorSetAlert(final AlertLevel alertLevel,
                          final ProximityAlert proximityAlert,
                          final AccelerometerAlert accelerometerAlert,
                          final CameraAlert cameraAlert) {
        this.alertLevel = alertLevel;
        this.proximityAlert = proximityAlert;
        this.accelerometerAlert = accelerometerAlert;
        this.cameraAlert = cameraAlert;
    }

    /**
     * Gets the alert level.
     * @return the {@link AlertLevel}
     */
    public AlertLevel getAlertLevel() {
        return this.alertLevel;
    }

    /**
     * Gets the proximity alert.
     * @return the {@link ProximityAlert}
     */
    public ProximityAlert getProximityAlert() {
        return this.proximityAlert;
    }

    /**
     * Gets the accelerometer alert.
     * @return the {@link AccelerometerAlert}
     */
    public AccelerometerAlert getAccelerometerAlert() {
        return this.accelerometerAlert;
    }

    /**
     * Gets the camera alert.
     * @return the {@link CameraAlert}
     */
    public CameraAlert getCameraAlert() {
        return this.cameraAlert;
    }
}
